version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL="postgresql://tdahung:trandinhanhhung@db_bookshop:5432/bookshop?schema=public"
    env_file:
      - .env

  db:
    image: postgres:latest
    container_name: db_bookshop
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=bookshop
      - POSTGRES_USER=tdahung
      - POSTGRES_PASSWORD=trandinhanhhung
