version: '3.7'

services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: tdahung
      POSTGRES_PASSWORD: trandinhanhhung # You should update this with a secure password
      POSTGRES_DB: bookshop
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - app-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  postgres-data:


networks:
  app-network:
